name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Paris
          plugin_languages: yes
          plugin_lines: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_repositories: yes
          plugin_repositories_featured: LionelVallet/ReHackt.Queryable.Extensions, LionelVallet/ReHackt.RazorEmails, LionelVallet/ReHackt.Extensions.Options.Validation
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 1
          plugin_stackoverflow_lines: 0
          plugin_stackoverflow_sections: ''
          plugin_stackoverflow_user: 7849405
          plugin_topics: yes
          plugin_topics_mode: icons
